### ISSUE TITLE
IDE Stuck

### ISSUE THREAD

**Issue by realgeoffrey** [jonathanlermitage/IconViewer#5]
When the image file is large, the entire IDE becomes slow. But after a while or close the large image, it becomes just ok again.

**Comment by jonathanlermitage** [comment]
@realgeoffrey Can you please provide a sample image? Thx.

**Comment by realgeoffrey** [comment]
like this:
![perfdog-android-1](https://github.com/jonathanlermitage/IconViewer/assets/7683037/241e63f9-a090-425c-885a-01438e1d3a9d).

It happened a lot. Almost every time I added a new image to webstorm(maybe a little large?), first of all, the image showed and then IDE had being slowly. Then I would try to shut down the image tab and maybe collapsed the image folder.

**Comment by jonathanlermitage** [comment]
@realgeoffrey I tried to add this image in a project in IntelliJ and it was instant. Can you please show your `idea.log`? (_Help_ > _Show log in explorer_)
