### ISSUE TITLE
Not working with new UI

### ISSUE THREAD

**Issue by Slion** [jonathanlermitage/IconViewer#6]
Could you guys get it to work with the new UI?

**Comment by jonathanlermitage** [comment]
@Slion Can you please give more information?  
What happens exactly, IDE name and version, plugin version, and your `idea.log` file (Help > Show Log in Explorer).

**Comment by Slion** [comment]
Sorry, it's working.
My issue was in fact with another plugin.
See: https://github.com/mistamek/Android-drawable-preview-plugin/issues/18#issuecomment-1898843875
